# Copy this file and rename to application.yml,
# Then modify the application configuration variables.
# Or add others, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
  STRIPE_SECRET_KEY: STRIPE_TEST_SECRET_KEY
  STRIPE_PUBLISHABLE_KEY: STRIPE_TEST_PUBLISHABLE_KEY

test:
  STRIPE_SECRET_KEY: STRIPE_TEST_SECRET_KEY
  STRIPE_PUBLISHABLE_KEY: STRIPE_TEST_PUBLISHABLE_KEY

production:
  APP_DOMAIN: arthurflix
  MAILER_HOST: arthurflix.herokuapp.com
  AWS_DIRECTORY: AWS_DIRECTORY
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  STRIPE_SECRET_KEY: STRIPE_SECRET_KEY
  STRIPE_PUBLISHABLE_KEY: STRIPE_PUBLISHABLE_KEY

staging:
  APP_DOMAIN: arthurflix-staging
  MAILER_HOST: arthurflix-staging.herokuapp.com
  AWS_DIRECTORY: AWS_DIRECTORY
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
  STRIPE_SECRET_KEY: STRIPE_TEST_SECRET_KEY
  STRIPE_PUBLISHABLE_KEY: STRIPE_TEST_PUBLISHABLE_KEY
